version: '3.8'

services:
  fayon-app:
    #image: crpi-dpwp83ztynfc9y23.cn-hangzhou.personal.cr.aliyuncs.com/fayon/fayon:v5c1126a
    image: crpi-dpwp83ztynfc9y23.cn-hangzhou.personal.cr.aliyuncs.com/fayon/fayon:vafd8a55
    container_name: fayon-app
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=Asia/Shanghai
      - HOST_NODE=11
      - GF_GCFG_FILE=./config/config.prod.yaml
    volumes:
      - ./logs:/app/logs
      - ./config:/app/config

  fayon-cron:
    #image: crpi-dpwp83ztynfc9y23.cn-hangzhou.personal.cr.aliyuncs.com/fayon/fayon:v5c1126a
    image: crpi-dpwp83ztynfc9y23.cn-hangzhou.personal.cr.aliyuncs.com/fayon/fayon:vafd8a55
    container_name: fayon-cmd
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=Asia/Shanghai
      - HOST_NODE=12
      - GF_GCFG_FILE=./config/config.prod.yaml
    volumes:
      - ./logs:/app/logs
      - ./config:/app/config
    command: ["/app/fayon", "--service=cmd"]

  fayon-consume:
    #image: crpi-dpwp83ztynfc9y23.cn-hangzhou.personal.cr.aliyuncs.com/fayon/fayon:v5c1126a
    image: crpi-dpwp83ztynfc9y23.cn-hangzhou.personal.cr.aliyuncs.com/fayon/fayon:vafd8a55
    container_name: fayon-consume
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=Asia/Shanghai
      - HOST_NODE=13
      - GF_GCFG_FILE=./config/config.prod.yaml
    volumes:
      - ./logs:/app/logs
      - ./config:/app/config
    command: ["/app/fayon", "--service=consume"]

