version: '3.8'

services:
  consul-server1:
    image: crpi-dpwp83ztynfc9y23.cn-hangzhou.personal.cr.aliyuncs.com/fayon/consul:hashicorp-1.17.0
    container_name: consul-server
    hostname: server
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./consul1.json:/consul/config/config.json:ro
      - ./data:/consul/data
      - ./logs:/consul/logs
      - /etc/localtime:/etc/localtime:ro
    environment:
      - CONSUL_ALLOW_PRIVILEGED_PORTS=
    ports:
      - "8500:8500"
      - "8600:8600/udp"
      - "8300:8300"
      - "8301:8301"
      - "8302:8302"
    command: agent