version: '3.8'

services:
  fayon-app:
    #image: crpi-dpwp83ztynfc9y23.cn-hangzhou.personal.cr.aliyuncs.com/fayon/fayon:v5c1126a
    image: crpi-dpwp83ztynfc9y23.cn-hangzhou.personal.cr.aliyuncs.com/fayon/fayon:v26d357c
    container_name: fayon-app
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=Asia/Shanghai
      - HOST_NODE=1
      - GF_GCFG_FILE=./config/config.prod.yaml
    volumes:
      - ./logs:/app/logs
      - ./config:/app/config
    # 移除了 depends_on: consul-server1

  fayon-cron:
    #image: crpi-dpwp83ztynfc9y23.cn-hangzhou.personal.cr.aliyuncs.com/fayon/fayon:v5c1126a
    image: crpi-dpwp83ztynfc9y23.cn-hangzhou.personal.cr.aliyuncs.com/fayon/fayon:v26d357c
    container_name: fayon-cmd
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=Asia/Shanghai
      - HOST_NODE=2
      - GF_GCFG_FILE=./config/config.prod.yaml
    volumes:
      - ./logs:/app/logs
      - ./config:/app/config
    command: ["/app/fayon", "--service=cmd"]
    # 移除了 depends_on: consul-server1

  fayon-consume:
    #image: crpi-dpwp83ztynfc9y23.cn-hangzhou.personal.cr.aliyuncs.com/fayon/fayon:v5c1126a
    image: crpi-dpwp83ztynfc9y23.cn-hangzhou.personal.cr.aliyuncs.com/fayon/fayon:v26d357c
    container_name: fayon-consume
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=Asia/Shanghai
      - HOST_NODE=3
      - GF_GCFG_FILE=./config/config.prod.yaml
    volumes:
      - ./logs:/app/logs
      - ./config:/app/config
    command: ["/app/fayon", "--service=consume"]
    # 移除了 depends_on: consul-server1

# 不再需要 consul-server1 服务和网络配置