version: '3.8'

services:
  fayon-app:
    #image: crpi-dpwp83ztynfc9y23.cn-hangzhou.personal.cr.aliyuncs.com/fayon/fayon:v5c1126a
    image: crpi-dpwp83ztynfc9y23.cn-hangzhou.personal.cr.aliyuncs.com/fayon/fayon:vafd8a55
    container_name: fayon-app
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=Asia/Shanghai
      - HOST_NODE=31
      - GF_GCFG_FILE=./config/config.prod.yaml
    volumes:
      - ./logs:/app/logs
      - ./config:/app/config
    # 移除了 depends_on: consul-server1

  fayon-cron:
    #image: crpi-dpwp83ztynfc9y23.cn-hangzhou.personal.cr.aliyuncs.com/fayon/fayon:v5c1126a
    image: crpi-dpwp83ztynfc9y23.cn-hangzhou.personal.cr.aliyuncs.com/fayon/fayon:vafd8a55
    container_name: fayon-cmd
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=Asia/Shanghai
      - HOST_NODE=32
      - GF_GCFG_FILE=./config/config.prod.yaml
    volumes:
      - ./logs:/app/logs
      - ./config:/app/config
    command: ["/app/fayon", "--service=cmd"]
    # 移除了 depends_on: consul-server1

  fayon-consume:
    #image: crpi-dpwp83ztynfc9y23.cn-hangzhou.personal.cr.aliyuncs.com/fayon/fayon:v5c1126a
    image: crpi-dpwp83ztynfc9y23.cn-hangzhou.personal.cr.aliyuncs.com/fayon/fayon:vafd8a55
    container_name: fayon-consume
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=Asia/Shanghai
      - HOST_NODE=33
      - GF_GCFG_FILE=./config/config.prod.yaml
    volumes:
      - ./logs:/app/logs
      - ./config:/app/config
    command: ["/app/fayon", "--service=consume"]
    # 移除了 depends_on: consul-server1

# 不再需要 consul-server1 服务和网络配置